---
abstract: 'write your files like Ingy, release like a regular dist'
author:
  - 'Carlos Lima <carlos@cpan.org>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::DZil: 0
  Test::More: 0.96
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-test2t
requires:
  Dist::Zilla::Role::FileMunger: 0
  Moose: 0
  namespace::autoclean: 0
resources:
  homepage: https://github.com/ingydotnet/dist-zilla-plugin-test2t-pm
  repository: https://github.com/ingydotnet/dist-zilla-plugin-test2t-pm.git
version: 0.001031
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@INGY/Git::GatherDir'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@INGY/CheckPrereqsIndexed'
      version: 0.009
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@INGY/CheckExtraTests'
      version: 0.015
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@INGY/@Filter/PruneCruft'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@INGY/@Filter/ManifestSkip'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@INGY/@Filter/MetaYAML'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::License
      name: '@INGY/@Filter/License'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@INGY/@Filter/Readme'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@INGY/@Filter/ExecDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@INGY/@Filter/ShareDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@INGY/@Filter/MakeMaker'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@INGY/@Filter/Manifest'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@INGY/@Filter/TestRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@INGY/@Filter/ConfirmRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@INGY/@Filter/UploadToCPAN'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@INGY/AutoPrereqs'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@INGY/ReadmeFromPod'
      version: 0.21
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@INGY/PkgVersion'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@INGY/MetaConfig'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@INGY/MetaJSON'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@INGY/NextRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@INGY/PodSyntaxTests'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@INGY/Test::Compile'
      version: 2.037
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@INGY/ReportVersions::Tiny'
      version: 1.10
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@INGY/TestMoreWithSubtests'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@INGY/GithubMeta'
      version: 0.42
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@INGY/@Git/Check'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@INGY/@Git/Commit'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@INGY/@Git/Tag'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@INGY/@Git/Push'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::ChangesFromYaml
      name: ChangesFromYaml
      version: 0.003
    -
      class: Dist::Zilla::Plugin::test2t
      name: test2t
      version: ~
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.006
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.006
